version: '3.6'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v2.5.0
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_ADMIN_SECRET: dev
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "unauthorized"
      HASURA_GRAPHQL_JWT_SECRET: '{ "type": "HS256",  "key": "this is a secret developpement key" }'
      HASURA_GRAPHQL_ADMIN_INTERNAL_ERRORS: "true"
volumes:
  db_data:
